USE ROLE SYSADMIN;

CREATE WAREHOUSE COMPUTE_WH WITH
WAREHOUSE_SIZE = 'SMALL'
WAREHOUSE_TYPE = 'STANDARD'
AUTO_SUSPEND = 300
AUTO_RESUME = TRUE;

GRANT USAGE ON WAREHOUSE COMPUTE_WH TO PUBLIC;

SHOW WAREHOUSES;
