GRANT USAGE ON DATABASE INGEST_STREAMING_DATA TO ROLE PUBLIC;

GRANT USAGE ON SCHEMA INGEST_STREAMING_DATA.PUBLIC TO ROLE PUBLIC;

GRANT SELECT ON TABLE INGEST_STREAMING_DATA.PUBLIC.TRANSACTIONS TO ROLE PUBLIC;

CREATE WAREHOUSE DATASCIENCE_WF WITH WAREHOUSE_SIZE = 'SMALL' WAREHOUSE_TYPE = 'STANDARD' AUTO_SUSPEND = 300 AUTO_RESUME = TRUE;

CREATE WAREHOUSE DBA_WF WITH WAREHOUSE_SIZE = 'XSMALL' WAREHOUSE_TYPE = 'STANDARD' AUTO_SUSPEND = 300 AUTO_RESUME = TRUE;

CREATE ROLE DATA_SCIENTIST;
GRANT USAGE ON WAREHOUSE DATASCIENCE_WF TO ROLE DATA_SCIENTIST;

CREATE ROLE DBAS;
GRANT USAGE ON WAREHOUSE DBA_WF TO ROLE DBAS;

CREATE USER DS_1 PASSWORD = 'DS_1' DEFAULT_ROLE = 'DATA_SCIENTIST' DEFAULT_WAREHOUSE = 'DATASCIENCE_WF' MUST_CHANGE_PASSWORD = FALSE;

CREATE USER DS_2 PASSWORD = 'DS_2' DEFAULT_ROLE = 'DATA_SCIENTIST' DEFAULT_WAREHOUSE = 'DATASCIENCE_WF' MUST_CHANGE_PASSWORD = FALSE;

GRANT ROLE DATA_SCIENTIST TO USER DS_1;

GRANT ROLE DATA_SCIENTIST TO USER DS_2;

CREATE USER DBA_1 PASSWORD = 'DBA_1' DEFAULT_ROLE = 'DBAS' DEFAULT_WAREHOUSE = 'DBA_WF' MUST_CHANGE_PASSWORD = FALSE;

CREATE USER DBA_2 PASSWORD = 'DBA_2' DEFAULT_ROLE = 'DBAS' DEFAULT_WAREHOUSE = 'DBA_WF' MUST_CHANGE_PASSWORD = FALSE;

GRANT ROLE DBAS TO USER DBA_1;
GRANT ROLE DBAS TO USER DBA_2;





